name: Create Pull Request Prerelease

on: 
 pull_request_target:

jobs:
  build:
    environment: gh-actions
    if: ${{ github.repository_owner == 'echowhoami' }}
    name: Build & Publish a Prerelease to the Adhoc Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: cat
        run: cat README.md

      - name: Upload runtime versions
        uses: actions/upload-artifact@v3
        with:
          name: runtime-versions.md
          path: runtime-versions.md

