name: Create Pull Request Prerelease

on: pull_request

jobs:
  build:
    if: ${{ github.repository_owner == 'echowhoami' }}
    name: Build & Publish a Prerelease to the Adhoc Registry
    runs-on: ubuntu-latest

    steps:
      - name: wait bro
        run: sleep 10

      - uses: actions/checkout@v4

      - name: Create filesss
        run: |
          cat README.md
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.event.pull_request.head.ref }}
